backend:
backend:
  name: github
  repo: kmof-prg/sokn-sa
  branch: main
  auth_type: pkce
  app_id: Ov23liPq2Mod4uPGciRe

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/home.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
